### ISSUE TITLE
Change buffer size / latency

### ISSUE THREAD

**Issue by josephernest** [levmin/ASIO2WASAPI#1]
Congratulations for this driver @levmin!
Could you add a GUI option in the configuration for buffer size / latency?
It seems to be locked to 4416 samples when using it with Ableton Live:

![image](https://user-images.githubusercontent.com/6168083/47883142-44dc0f80-de2c-11e8-8527-a36ee48b44cf.png)

Or maybe could you build a new version with buffer size = 512 or 1024 samples?

Thank you in advance @levmin!

**Comment by isavcic** [comment]
Shameless bump!

**Comment by Falcosoft** [comment]
This issue is fixed in this fork:
https://github.com/Falcosoft/ASIO2WASAPI

**Comment by levmin** [comment]
Thanks. If you want to, you can create a pull request. I would then merge your changes. - Lev

**Comment by josephernest** [comment]
@Falcosoft @levmin A merge would be great!

**Comment by Falcosoft** [comment]
Hi,
Of course I'm happy to make a pull request but the main question is further development and maintenance. I have no access to original repository but I have further plans for adding new features like WASAPI shared mode support and so on.
Added features most likely can create new issue reports that I could only handle in my fork. Also I can make new releases only in my repository. 
So I'm not sure what would be the best long time solution.

**Comment by levmin** [comment]
>>
have no access to original repository
<<

What do you mean? You don’t have access to GitHub - levmin/ASIO2WASAPI: A universal ASIO driver - an interface between ASIO and WASAPI APIs<https://github.com/levmin/ASIO2WASAPI>?

**Comment by Falcosoft** [comment]
I have read-only access to https://github.com/levmin/ASIO2WASAPI so I cannot work 'directly' with it. 
Which means I cannot commit to it directly, cannot close resolved issues there, and cannot make new releases there among others.

**Comment by levmin** [comment]
> Congratulations for this driver @levmin! Could you add a GUI option in the configuration for buffer size / latency? It seems to be locked to 4416 samples when using it with Ableton Live:
> 
> ![image](https://user-images.githubusercontent.com/6168083/47883142-44dc0f80-de2c-11e8-8527-a36ee48b44cf.png)
> 
> Or maybe could you build a new version with buffer size = 512 or 1024 samples?
> 
> Thank you in advance @levmin!

@josephernest @isavcic I am sorry, I just noticed your comments. My github account is linked to my old email address that gets tons of spam and the spam filter is configured very aggressively. I need to update it to a better email address. 

Anyway, I did this and some other digital audio work starting from 2005 I think to maybe 2016. I wrote that shim driver to work with my ASIO Windows Media Player plugin, in situations where there was no vendor-supplied ASIO driver.  My interests changed after that,  but perhaps @Falcosoft and/or somebody else would be willing to continue to maintain this code. I need to learn how to make this a more collaborative effort.

**Comment by Falcosoft** [comment]
Thanks, I have got your invitation and accepted it.
Soon I will be ready with some new features and then I upload them.

**Comment by levmin** [comment]
Very good. I think one of the first steps should be to migrate this project to a more recent version of Visual Studio. It looks like I used VS2012 back then. I did a quick check that the code cleanly compiles with VS2022, but will leave it up to you to decide which version of the VS to use.

**Comment by Falcosoft** [comment]
Hi,
The truth is that any later versions of Visual Studio can open/convert VS 2012 project and solution files without any problems.
(They do a one time conversion at first opening.)
But unfortunately this is not true the other way around. So in it's current form the solution and projects can be opened with any VS versions from VS 2012 to VS 2022. If we do what you suggest (that is migrate the solution and projects to one of the later versions) we would not get any new 'compatibility' advantage but only lose compatibility with older versions. 
But of course this is just an opinion.

**Comment by levmin** [comment]
You are right in terms of compatibility. Technically, one can have e.g. VS2012 and VS2022 installed side by side and choose not to update on opening the project for the first time in VS2022. Then, the build process will continue to use the VS2012 toolchain. As I said, I will leave it up to you which VS version to use. I do not expect to be working on this project again.

**Comment by Falcosoft** [comment]
Thanks again for your work and I wish you the best in your new adventures :)

**Comment by Falcosoft** [comment]
I think this issue can be closed since new releases contain solution for this problem.
