### ISSUE TITLE
Can´t download File from Sourceforge

### ISSUE THREAD

**Issue by Edelplastic** [levmin/ASIO2WASAPI#23]
I tried to download the 1.0 ZIP-File from Sourceforge with different browsers and after counting down the timer, it opened a new site with "create your own project" Does the File still exist there?

**Comment by Falcosoft** [comment]
Hi,
I do not know if the driver exists there or not but you can download the same 1.0 version from the 1st commit of this repo:
https://github.com/levmin/ASIO2WASAPI/tree/32303733ee89e1570cfd9333e43a8324a71382fc
(It's in the release folder).
But I suggest that you should use the newest version from the release section instead:
https://github.com/levmin/ASIO2WASAPI/releases

**Comment by Edelplastic** [comment]
Thank you very much - I will give it a try.
