### ISSUE TITLE
[REQ] License file fix

### ISSUE THREAD

**Issue by MarcoRavich** [levmin/ASIO2WASAPI#24]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Tools page](https://github.com/forart/HyMPS/blob/main/A_Tools.md#--) \ [ASIO subsection](https://github.com/forart/HyMPS/blob/main/A_Tools.md#asio-)), can you please fix the license file ?

Although it may sounds like a minor aspect, license file uncompliance causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/levmin/ASIO2WASAPI/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/levmin/ASIO2WASAPI/?label=LICENSE)

Anyway you can easily set a "correct" one through the GH's license wizard tool.

Last but not least, let us know - in your opinion - how we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by Falcosoft** [comment]
Hi,
As you may have noticed this repository has become a pull-request only repository nowadays.
I have become the maintainer of ASIO2WASAPI and actually I'm working actively on the repository of my fork:
https://github.com/Falcosoft/ASIO2WASAPI

In practice it proved to be rather tiresome to maintain 2 repositories of the same code base so I decided to finish the pull requests to levmin/ASIO2WASAPI and only maintain my own fork. So I have fixed the license there. It seems to be working:
https://flat.badgen.net/github/license/Falcosoft/ASIO2WASAPI?label=LICENSE

**Comment by MarcoRavich** [comment]
Thanks, I've updated the list with the other repository link (and relative badge).
