### ISSUE TITLE
've encountered a 2019 error 

### ISSUE THREAD

**Issue by kinghelong** [levmin/ASIO2WASAPI#3]
I'm a beginner, and I'm using your project in my own project. I've encountered a 2019 error after writing this piece of code:

LPUNKNOWN lp = NULL;
HRESULT hr = 0;
ASIO2WASAPI asio(lp, &hr);

Could you please provide some guidance on how to resolve this error?

**Comment by levmin** [comment]
Sorry, I didn't notice this comment when it was posted. I am no longer involved in digital audio matters, have not touched this code for 6+ years and have little recollection of what it does. I am hoping for somebody to take this project over.
